name: Firmware CI with Validation

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-flash-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt || echo "No Python deps required"

    - name: Install firmware tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential dfu-util

    - name: Build firmware (simulated)
      run: |
        echo "Simulating firmware build..."
        mkdir -p firmware
        echo "dummy firmware binary" > firmware/output.hex

    - name: Flash firmware to device (simulated)
      run: |
        echo "Simulating firmware flash..."
        ls -l firmware/output.hex
      continue-on-error: true  # Always pass even without hardware

    - name: Wait for device reboot (simulated)
      run: sleep 2

    - name: Run RPM validation tests (simulation mode)
      run: |
        echo "PWM,ExpectedRPM,ActualRPM,Pass" > tacho_validation_log.csv
        echo "20,1000,995,True" >> tacho_validation_log.csv
        echo "40,2000,2010,True" >> tacho_validation_log.csv
        echo "60,3000,2980,True" >> tacho_validation_log.csv
        echo "80,4000,3995,True" >> tacho_validation_log.csv
        echo "100,5000,5020,True" >> tacho_validation_log.csv
        cat tacho_validation_log.csv

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: tacho-validation-logs
        path: tacho_validation_log.csv
