name: Firmware CI with Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-flash-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r tests/requirements.txt || echo "No Python deps required"

    - name: Install firmware tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential dfu-util

    - name: Build firmware
      run: |
        cd firmware
        make clean && make

    - name: Flash firmware to device
      run: |
        dfu-util -a 0 -D firmware/output.hex
      continue-on-error: true  # For simulation or mock

    - name: Wait for device reboot
      run: sleep 5

    - name: Run RPM validation tests
      run: |
        python tests/validate_tacho_vs_pwm.py

    - name: Archive logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: tacho-validation-logs
        path: tacho_validation_log.csv
